# This file was generated by GoReleaser. DO NOT EDIT.
cask "pando" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b0fd4d3772d3e746c9c2c7852d7a6f48a21c463cc77365614ee9bc55ddf766c2"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f16106c6ee4726790433b9bead4c3c9863f429150cf4b08097163e9e5667830f"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "03eed3c0a2f2695c666e4b0b9a5f983b93da22cc29af5c390a095795efec23b3"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "629470af58dc28664e13c2fd792547bf8b2f9393a07337bbaa9bac3200b7cef3"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pando"
  desc "Deploy applications to a host you own"
  homepage "https://github.com/bemeek-io/pando"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pando"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pando"]
    end
  end

  # No zap stanza required
end
