# This file was generated by GoReleaser. DO NOT EDIT.
cask "pando" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "9ff5914b53f19190c17fb4fa1083400b355aaa913b97b5e53d03a91616cde8eb"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cece77d83d3f86b524ff67f004d00a5e3144091f621f806cec170dc4af919d0e"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f646d0e20ba94aba28d2d66000062b5dbde550bedf3a3bc03b2c1f4ee02320f6"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1fbea6b928eb766436b2a43b5575a4dccf72baad793e33861212b2e0630eb02"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pando"
  desc "Deploy applications to a host you own"
  homepage "https://github.com/bemeek-io/pando"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pando"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pando"]
    end
  end

  # No zap stanza required
end
