# This file was generated by GoReleaser. DO NOT EDIT.
cask "pando" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "02e417dfee51c73c37877d6ada6776c20c3154cf36a39aea5d8513dbcea9cfcf"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "163fc93c5f9360b91ddb9bab9fa1a2cd888956c497dd37c5709404b750bec159"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c2efaf3e88384cde8b3e77ed9ca448740630e4185737116dd10c4897f81aad96"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5a5384c22464e2abb3fecb13c6898f0430eb7837d9b6a1902aec3a533395d85"
      url "https://github.com/bemeek-io/pando/releases/download/v#{version}/pando_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pando"
  desc "Deploy applications to a host you own"
  homepage "https://github.com/bemeek-io/pando"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pando"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pando"]
    end
  end

  # No zap stanza required
end
